# Generated by Django 4.1.7 on 2023-03-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
        ),
    ]
