# Generated by Django 4.1.5 on 2023-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
