# Generated by Django 4.1.7 on 2023-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Cотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Льгота', 'verbose_name_plural': 'Льготы'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=1000, null=True, verbose_name='Цена'),
        ),
    ]
